---

# http://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable
aptcachetime: 3600
locale: "en_US.UTF-8"
timezone: "America/Los_Angeles"

# Role: gantsign.atom
# https://galaxy.ansible.com/gantsign/atom/
users:
  - username: "{{ ansible_env.USER }}"
    atom_packages:
      - sync-settings
      - minimap
      - linter
      - atom-beautify
      - file-icons
      - pigments
      - autocomplete-python
      - atom-html-preview
      - markdown-preview
      - markdown-preview-plus
      - language-python
      - language-ruby-on-rails
      - language-json
    atom_config:
      "*":
        core:
          projectHome: "{{ ansible_env.HOME }}"
          telemetryConsent: no
        editor:
          tabType: soft
          showIndentGuide: true
          showInvisibles: true

# Root Database Passwords
# Roles: mysql57, PotgreSQL-Install
database:
  mysql_user: root
  postgres_user: "{{ ansible_env.USER }}"
  password: secret

# Role: wiki
wiki:
  # version is git branch
  version: 1.4.0-pre
  mysql_user: wiki
  mysql_password: wiki_password
  mysql_database: local_wiki
  admin_users: KlenwellAdmin

# Role: gmailx
# To set password, copy role dist vars file and update:
# cp -v roles/gmailx/vars/main.yml{-dist,}
gmailx:
  goto: roles/gmailx/vars/main.yml

# Role: apache2-php
vhosts:
  - template: standard
    vhost: "default70.dev"
    path: "{{ ansible_env.HOME }}/projects/default-7.0"
  - template: standard
    vhost: "default56.dev"
    path: "{{ ansible_env.HOME }}/projects/default-5.6"
    php: "5.6"

# Role: desktop-autostart
desktop_autostart:
  add:
    - { name: Tilda , exec: /usr/bin/tilda }
  remove:
    #- deja-dup-monitor.desktop
    - onboard-autostart.desktop
    - orca-autostart.desktop
    - vino-server.desktop

# Role: chromium
chromium:
  set_default: true
  policy: false
  extensions: false

# Role: php-phar-tools
php_phar_tools:
  php_cs_fixer: true
  phpcpd: true
  sami: true
  robo: true
  phpmd: true
  phpunit: true
  codeception: true
  cssprites: true
  wpcli: true
