---
dependencies: []

galaxy_info:
  author: kylebebak
  description: "Tmux installation for Ubuntu"
  license: MIT
  min_ansible_version: 1.9.4
  platforms:
    - name: Ubuntu
      versions:
      - all
  galaxy_tags:
    - development
    - tmux
