#
# Install Jenkins jobs.
# Docs: https://docs.ansible.com/ansible/jenkins_job_module.html
#
---
# Source: https://stackoverflow.com/a/34522653/1093087
- name: "Wait for Jenkins to be available."
  uri:
    url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 1

- name: Install Jenkins backup job.
  jenkins_job:
    config: "{{ lookup('template', 'jobs/backup.xml.j2') }}"
    name: Local Wiki Backup
    url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}"
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"

- name: Make .env folder for jenkins.
  file:
    path: "{{ jenkins_home }}/.env"
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0755
  become: true

- name: Install dotenv file for fab script.
  template:
    src: local-wiki.env.j2
    dest: "{{ jenkins_home }}/.env/local-wiki.env"
    owner: jenkins
    group: jenkins
    force: no
  become: true

- name: Create bin folder for fab script.
  file:
    path: "{{ jenkins_home }}/jobs/Local\ Wiki\ Backup/fab"
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0775
  become: true

- name: Install fab script.
  template:
    src: fab_backup.py.j2
    dest: "{{ jenkins_home }}/jobs/Local\ Wiki\ Backup/fab/fab_backup.py"
    owner: jenkins
    group: jenkins
    mode: 0644
  become: true
