#
# To run playbook:
#   ansible-playbook ansible-desktop.yml --ask-become-pass
#
# To run specific roles, add tag dev:
#   - { role: wiki, tags: dev }
# Then run playbook with --tags option:
#   ansible-playbook ansible-desktop.yml --ask-become-pass --tags dev -v
#
# Source: https://github.com/Benoth/ansible-ubuntu/blob/1786382/ansible-desktop.yml
#
---
- name: Ubuntu desktop environment playbook
  hosts: localhost
  roles:
    # Common
    - { role: locales, become: true }
    - { role: common, become: true, tags: dev }
    - { role: java-openjdk, become: true }
    - { role: phantomjs, become: true }

    # Desktop
    - { role: desktop, become: true }
    - { role: desktop-cleanup, become: true }
    - { role: desktop-preferences-unity }
    - { role: desktop-autostart, become: true }
    - { role: indicator-sysmonitor, become: true }
    - { role: atom, become: true }
    - { role: firefox, become: true }
    - { role: google-chrome, become: true }
    - { role: chromium, become: true }
    - { role: gimp, become: true }
    # - { role: shutter, become: true }     # Screenshot Tool
    # - { role: libreoffice, become: true }
    # - { role: gdrive, become: true }
    # - { role: remarkable, become: true }  # Markdown Editor
    # - { role: spotify, become: true }
    # - { role: vokoscreen, become: true }  # Screencast Creator

    # Developer
    - { role: home-sweet-home }
    - { role: ssh-keys }
    - { role: kylebebak.tmux }
    - { role: virtualbox, become: true }
    - { role: gmailx, tags: dev }
    # - { role: docker, become: true }
    # - { role: vagrant, become: true }
    # - { role: nodejs, become: true }
    # - { role: gulp }                      # JS Automation Tool
    # - { role: bower }                     # JS Package Manager
    # - { role: webpack }                   # JS Asset Bundler
    # - { role: memcached, become: true }
    # - { role: redis, become: true }
    # - { role: filezilla, become: true }
    # - { role: mysql-workbench, become: true }
    # - { role: remmina, become: true }     # Remote Desktop Client
    # - { role: browsersync }               # Browser Testing Tool
    # - { role: skype, become: true }

    # Google App Engine / Python
    - { role: python, become: true }        # Required by atom Role
    - { role: avanov.pyenv, become: true }
    - { role: maciejzasada.gae, gae_language: 'python', gae_version: "1.9.54" }

    # LAMP Server
    - { role: apache2, become: true }
    - { role: php, become: true }
    - { role: php-pecl, become: true }
    - { role: php-phar-tools, become: true }
    - { role: apache2-php, become: true }
    - { role: mysql57, become: true }
    - { role: composer, become: true }

    # Ruby / Rails
    - { role: zzet.rbenv }
    - { role: bbatsche.PostgreSQL-Install, postgres_version: '9.5' }

    # Jenkins Server
    - { role: geerlingguy.jenkins, become: true }
    - { role: jenkins-pyenv, become: true }

    # Personal Local Sites
    - { role: wiki }
    - { role: mushpup, become: true }

    # Epilogue
    - { role: afterword, tags: dev }
