#
# Config ssh keys.
#
---
# Source: https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/
- name: Generate SSH keys
  command: "ssh-keygen -t rsa -b 4096 -f {{ ansible_env.HOME }}/.ssh/{{ item }} -C \"{{ item }}\" -N ''"
  with_items:
    - id_rsa
    - github-klenwell
    - github-tatwell
    - bitbucket-klenwell
  # Only run if file does not exist (i.e. creates returns true)
  args:
      creates: "{{ ansible_env.HOME }}/.ssh/{{ item }}"

- name: Create .ssh/config file for multiple accounts
  template:
    src: ssh-config.j2
    dest: "{{ ansible_env.HOME }}/.ssh/config"
