---
# tasks file for ansible-role-gae install task
- name: create temp directory to work in
  file: state=directory path={{ gae_temp_dir }}

- name: download Google App Engine installation package
  get_url: url={{ gae_download_url_go }} dest={{ gae_temp_dir }}/gae.zip

- name: unzip the downloaded file
  unarchive: src={{ gae_temp_dir }}/gae.zip copy=no dest={{ gae_install_dir }}

- name: export path
  sudo: yes
  lineinfile: >
    dest=/etc/environment
    state=present
    backrefs=yes
    regexp='PATH=(["]*)((?!.*?{{gae_install_dir}}/go_appengine).*?)(["]*)$'
    line="PATH=\1\2:{{gae_install_dir}}/go_appengine\3"
  # notify:
  #   - restart shell