---
# tasks file for ansible-role-gae install task
- name: install unzip
  apt: name=unzip update_cache=no
  become: true

- include: install-python.yml
  when: gae_language=='python'

- include: install-java.yml
  when: gae_language=='java'

- include: install-php.yml
  when: gae_language=='php'

- include: install-go.yml
  when: gae_language=='go'
