---
- name: install build depends
  yum: name={{ item }} state=present
  with_items:
    - bzip2
    - gcc
    - git
    - libffi-devel
    - libyaml-devel
    - openssl-devel
    - readline-devel
    - zlib-devel
  become: true

- name: install extra build depends
  yum: name={{ item }} state=present
  with_items: '{{ rbenv_extra_depends }}'
  become: true
