#
# Install Jenkins jobs.
# Docs: https://docs.ansible.com/ansible/jenkins_job_module.html
#
---
- name: Python dependencies for jenkins_job.
  pip: name={{ item }} state=latest
  with_items:
    - python-jenkins
    - lxml

- name: Install Jenkins jobs.
  jenkins_job:
    config: "{{ lookup('file', 'jobs/' + item + '.xml') }}"
    name: Good Morning Jenkins
    url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}"
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
  with_items: "{{ jenkins_jobs }}"
