---
- name: Use pyenv role to install pyenv for jenkins
  include_role:
    name: avanov.pyenv
  vars:
    pyenv_path: "{{ jenkins_home }}/pyenv"
    pyenv_owner: jenkins
    pyenv_update_git_install: no
    pyenv_enable_autocompletion: no
    pyenv_python_versions:
      - "2.7.8"
    pyenv_virtualenvs:
      - venv_name: "latest_v2"
        py_version: "2.7.8"
  
- name: restart jenkins
  service: name=jenkins state=restarted
