---
- name: Install
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=86400
  with_items:
    - postgresql-{{ postgres_version }}
    - postgresql-contrib-{{ postgres_version }}
    - python-psycopg2

    # For pg gem
    - libpq-dev
  become: yes
  register: postgres_install

- include: lockdown.yml
  when: postgres_install | changed

- name: Add Adminpack
  postgresql_ext:
    name: adminpack
    db:   postgres
    login_user:     "{{ db_admin }}"
    login_password: "{{ db_pass }}"
