#
# Install Mushpup locally.
# https://github.com/klenwell/mushpup
#
---
- name: "Create document root for local site"
  file: path="/var/www/mushpup" state=directory
  register: projects_directory_created

- name: "Create local mushpup home"
  template:
    src: index.html.j2
    dest: "/var/www/mushpup/index.html"
    mode: 0644
  become: true

- name: Set up local virtual host for Apache
  template:
    src: apache.conf.j2
    dest: "/etc/apache2/sites-available/mushpup.conf"
  become: true

- name: Enable wiki virtual host
  shell: "a2ensite mushpup.conf"
  notify: Restart Apache2
  become: true

- name: Add wiki to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1     mushpup'
    line: '127.0.0.1     mushpup'
    state: present
  become: true

- name: Mushpup announcement
  debug: msg="Mushpup setup complete. See http://mushpup/."
